### ISSUE TITLE
Process does not terminate on close

### ISSUE THREAD

**Issue by zcmoore** [Progressive-Learning-Platform/PLPTool6#3]
After closing the FX frame with the X button, the process continues to run. It should terminate.

**Comment by zcmoore** [comment]
I can no longer reproduce this issue on master (f008343)

Is anyone else still having this problem?

**Comment by tobielf** [comment]
@tanpuresiddhant Try to reproduce this bug if it doesn't exist anymore, close this issue. Due: next Saturday(Sept 9, 2017).

**Comment by tobielf** [comment]
@tanpuresiddhant Please update your progress by adding a comment below.

**Comment by tanpuresiddhant** [comment]
I tried to reproduce the bug on my machine but couldn't find it. All processes closed after closing the application(clicking on the x button).
